name: Run Tests

on:
  push:
    branches:
      - main   # или другая ветка, в зависимости от того, как вы пушите изменения
  pull_request:
    branches:
      - main   # запустит тесты на pull request в main

jobs:
  tests:
    runs-on: ubuntu-latest  # можно использовать другой образ, если хотите

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user -d test_db"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.9

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 mesa-utils xvfb
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 &

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U test_user; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      - name: Run tests
        run: |
          pytest --cov=gui --cov=db --cov-report=html tests

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov
